"""
Django settings for PoxSearchDB project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, dj_database_url
from decouple import config
import sys
import xyzservices.providers as xyz

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# GDAL_LIBRARY_PATH = r".venv\Lib\site-packages\osgeo\gdal.dll"
# SPATIALITE_LIBRARY_PATH = r"C:\Users\Riley\Documents\Sync\PycharmProjects\ScienceExtractionDjangoProject\spatialite\mod_spatialite.dll"
# SPATIALITE_LIBRARY_PATH = r"C:\OSGeo4W\bin\mod_spatialite.dll"
# GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer an explicit environment variable. If not found, try reading from
# a .env via python-decouple. If still missing, behave as follows:
#  - in DEBUG mode: generate a random secret key (safe for local/dev only)
#  - in non-DEBUG (production): raise an error to avoid insecure defaults
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

SECRET_KEY = os.getenv("SECRET_KEY") or config("SECRET_KEY", default=None)

if not SECRET_KEY:
    if DEBUG:
        # generate a throwaway key for local development / tests
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY not found. Set the SECRET_KEY environment variable or provide it in a .env for production."
        )

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'extracteddata.apps.ExtracteddataConfig',
    'django.contrib.gis',
    'leaflet',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PoxSearchDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PoxSearchDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,        # persistent connections (important for Render)
        ssl_require=True
    )
}

DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# Only set psycopg2-specific connection OPTIONS when psycopg2 is available.
# Passing psycopg2 kwargs like 'sslmode' to other adapters (e.g. psycopg 3)
# can raise TypeError: Connection() got an unexpected keyword argument 'sslmode'.
try:
    import psycopg2  # type: ignore
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "require",
        "channel_binding": "require",  # matches Neon's requirements
        "prepare_threshold": 0,        # required for PgBouncer / pooler
    }
except Exception:
    # psycopg2 not installed (maybe using psycopg 3 or another adapter).
    # Leave OPTIONS empty so Django won't pass unsupported kwargs.
    DATABASES["default"]["OPTIONS"] = {}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
}

# Redirect users to the site home after login/logout instead of the default /accounts/profile/
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Leaflet Map Configuration
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (20.0, 0.0),
    'DEFAULT_ZOOM': 3,
    'MIN_ZOOM': 2,
    'MAX_ZOOM': 18,
    'TILE_PROVIDERS': {
        'OpenStreetMap': 'OpenStreetMap.Mapnik',
        'OpenTopoMap': 'OpenTopoMap',
        'Esri WorldImagery': 'Esri.WorldImagery',
        'CartoDB Positron': 'CartoDB.Positron',
    },
    'CLUSTER_OPTIONS': {
        'chunkedLoading': True,
        'chunkInterval': 200,
        'chunkDelay': 50,
        'maxClusterRadius': 80,
        'spiderfyOnMaxZoom': True,
        'showCoverageOnHover': False,
        'zoomToBoundsOnClick': True,
        'disableClusteringAtZoom': 12
    },
    'MARKER_STYLE': {
        'radius': 6,
        'fillColor': '#3388ff',
        'color': '#fff',
        'weight': 1,
        'opacity': 1,
        'fillOpacity': 0.7
    }
}
